### List all games as a JSON response
GET http://localhost:3000/api/games

### Add a new game, data in body
POST http://localhost:3000/api/games
Content-Type: application/json

{
    "title": "Solitaire", 
    "price": 1, 
    "genre": "Cardgame", 
    "id": "abc"
}

### Delete specified game by id in url
DELETE http://localhost:3000/api/games/1

### Update specified game by id in url, data in body
PUT http://localhost:3000/api/games/abc
Content-Type: application/json

{
    "title": "Solitaire modified",
    "price": 2,
    "genre": "Cardgame",
    "id": "abc"
}